/**
 * Purge fake/fallback fight records from the database.
 *
 * Fake fights were generated by generateFallbackFullFightCard() when both
 * Tapology and UFC.com scrapers failed. The PostEventProcessor then randomly
 * assigned results to those fights, always writing:
 *   endingRound: 1, endingTime: "2:30"
 *
 * Real fights end at varied rounds and times. Any event where ALL fights share
 * exactly { endingRound: 1, endingTime: "2:30" } almost certainly had its
 * entire fight card fabricated.
 *
 * Usage:
 *   npm run fights:purge-dry     # dry-run (shows what would be deleted)
 *   npm run fights:purge         # actually deletes
 */

import "dotenv/config";
import { PrismaClient } from "../generated/prisma";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";

const DRY_RUN = !process.argv.includes("--execute");

function buildConnectionString(): string {
  const raw = (process.env.DIRECT_URL || process.env.DATABASE_URL)!;
  try {
    const u = new URL(raw);
    u.searchParams.delete("channel_binding");
    u.searchParams.set("uselibpqcompat", "true");
    u.searchParams.set("sslmode", "require");
    return u.toString();
  } catch {
    return raw;
  }
}

function freshClient() {
  const pool = new Pool({
    connectionString: buildConnectionString(),
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 60_000,
    idleTimeoutMillis: 30_000,
    max: 5,
  });
  const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });
  const cleanup = async () => {
    try { await prisma.$disconnect(); } catch {}
    try { await pool.end(); } catch {}
  };
  return { prisma, cleanup };
}

async function main() {
  console.log(`\n=== Purge Fake Fights (${DRY_RUN ? "DRY RUN" : "EXECUTE"}) ===\n`);

  const { prisma, cleanup } = freshClient();

  try {
    // Find all fights with the fake-result signature set by PostEventProcessor
    const suspectFights = await prisma.fight.findMany({
      where: {
        endingRound: 1,
        endingTime: "2:30",
        winnerId: { not: null },
      },
      select: {
        id: true,
        eventId: true,
        fighter1: { select: { name: true } },
        fighter2: { select: { name: true } },
        event: { select: { name: true, isProcessed: true } },
      },
    });

    if (suspectFights.length === 0) {
      console.log("No fights with fake signature found. Database is clean.");
      return;
    }

    console.log(`Found ${suspectFights.length} fight(s) with fake signature { endingRound: 1, endingTime: "2:30" }\n`);

    // Group by event
    const byEvent = new Map<string, typeof suspectFights>();
    for (const f of suspectFights) {
      const list = byEvent.get(f.eventId) ?? [];
      list.push(f);
      byEvent.set(f.eventId, list);
    }

    // Identify events where EVERY fight has the fake signature
    const fakeEventIds: string[] = [];

    for (const [eventId, fakes] of byEvent.entries()) {
      const total = await prisma.fight.count({ where: { eventId } });
      const eventName = fakes[0].event.name;

      if (total === fakes.length) {
        fakeEventIds.push(eventId);
        console.log(`[FAKE] ${eventName}`);
        console.log(`       All ${total} fight(s) are fake.`);
        for (const f of fakes) {
          console.log(`       - ${f.fighter1.name} vs ${f.fighter2.name}`);
        }
        console.log();
      } else {
        console.log(`[SKIP] ${eventName} — ${fakes.length}/${total} fights suspect (mixed real+fake data, skipping)`);
        console.log();
      }
    }

    if (fakeEventIds.length === 0) {
      console.log("No fully-fake events found after analysis. Nothing to delete.");
      return;
    }

    console.log(`Summary: ${fakeEventIds.length} event(s) with entirely fake fight cards.`);

    if (DRY_RUN) {
      console.log("\nDry-run mode — no changes made.");
      console.log("Re-run with --execute (npm run fights:purge) to delete these fights and reset event state.");
      return;
    }

    // Execute purge
    console.log("\nDeleting fake fights and resetting event processing state...");

    for (const eventId of fakeEventIds) {
      const deleted = await prisma.fight.deleteMany({ where: { eventId } });
      await prisma.event.update({
        where: { id: eventId },
        data: { isProcessed: false },
      });
      console.log(`  Deleted ${deleted.count} fight(s) from event ${eventId}, reset isProcessed → false.`);
    }

    console.log(`\nPurge complete. ${fakeEventIds.length} event(s) cleaned.`);
    console.log("IMPORTANT: Elo ratings corrupted by fake fights are NOT automatically reverted.");
    console.log("           Run `npm run elo:recalculate` to rebuild all Elo ratings from scratch.");
  } finally {
    await cleanup();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
